### ISSUE TITLE
Moment JS Error in Logs 

### ISSUE THREAD

**Issue by marct83** [timeoff-management/application#239]
This Error keeps showing up in the logs. Curious what might be causing it:

```Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i: 2018, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/home/tremm1/Code/application/node_modules/moment/moment.js:324:94)
    at configFromString (/home/tremm1/Code/application/node_modules/moment/moment.js:2366:11)
    at configFromInput (/home/tremm1/Code/application/node_modules/moment/moment.js:2592:9)
    at prepareConfig (/home/tremm1/Code/application/node_modules/moment/moment.js:2575:9)
    at createFromConfig (/home/tremm1/Code/application/node_modules/moment/moment.js:2542:40)
    at createLocalOrUTC (/home/tremm1/Code/application/node_modules/moment/moment.js:2629:12)
    at Function.createUTC [as utc] (/home/tremm1/Code/application/node_modules/moment/moment.js:92:12)
    at promise_adjustment_and_carry_over_for_year (/home/tremm1/Code/application/lib/model/mixin/user/absence_aware.js:525:19)
    at Promise.try.then (/home/tremm1/Code/application/lib/model/mixin/user/absence_aware.js:510:24)
    at tryCatcher (/home/tremm1/Code/application/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/tremm1/Code/application/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/tremm1/Code/application/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/home/tremm1/Code/application/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/home/tremm1/Code/application/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/tremm1/Code/application/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/tremm1/Code/application/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)```

**Comment by vpp** [comment]
hi @marct83 this is moment.js is unhappy with how it is used. It does not affect the app at this moment but will do when the dependencies are bumped up.

Although that warning needs to be fixed.

So lets keep that ticket to address it.
