### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by marct83** [timeoff-management/application#246]
Have been seeing this in our logs. I'm unsure what is being done in the UI when this is happening.
Any idea what might cause this?

GET /fonts/fontawesome-webfont.eot? 304 0.281 ms - -
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1003:13)
    at TCP.onread (net.js:620:25)

**Comment by vpp** [comment]
@marct83 consider running app in "cluster" mode so workers restart each other if needed:

node bin/wwww_cluster

**Comment by marct83** [comment]
We have the app running in Kubernetes so it it already restarts the container if it crashes. So it does recover which is good. But having it crash continually/intemitently on this same error is troubling.

**Comment by vpp** [comment]
@marct83 so it does crash every single time you open Team view page?

**Comment by vpp** [comment]
Just saw you mentioned “intermittently”.

Is it possible that process does not have enough memory?

**Comment by marct83** [comment]
Verified lots of available memory.

**Comment by vpp** [comment]
@marct83 how many users do you have in that particular Team view page?

**Comment by marct83** [comment]
19

**Comment by vpp** [comment]
well.. that is usual size..

simple suggestion but I assume you start the app with command like this:

`nohup node bin/wwww_cluster >> /path/to/log/file  2>&1 &`
