### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by k-wozniak** [timeoff-management/application#304]
I have installed the timeoff-management and as instructed in readme file and I have run the tests.
The outcome of the test 4, 16, 35, 38, 39, 42, 49, 54, 57, 59, 61 etc. is as following (taken from the outcome of test 4 but repeats on each following test):

`CRUD for bank holidays`
    `4) Performing registration  process`
`Unhandled rejection TypeError: Cannot read property 'get' of undefined
    at /mnt/c/Users/kwozniak/Documents/application-master-test/t/lib/open_page.js:14:5
    at tryCatcher (/mnt/c/Users/kwozniak/Documents/application-master-test/node_modules/bluebird/js/main/util.js:26:23)
    at ret (eval at <anonymous> (/mnt/c/Users/kwozniak/Documents/application-master-test/node_modules/bluebird/js/main/promisify.js:163:12), <anonymous>:13:39)
    at Context.<anonymous> (/mnt/c/Users/kwozniak/Documents/application-master-test/t/integration/bank_holidays/crud_bank_holiday.js:36:5)
    at callFnAsync (/mnt/c/Users/kwozniak/Documents/application-master-test/node_modules/mocha/lib/runnable.js:371:21)
    at Test.Runnable.run (/mnt/c/Users/kwozniak/Documents/application-master-test/node_modules/mocha/lib/runnable.js:318:7)
    at Runner.runTest (/mnt/c/Users/kwozniak/Documents/application-master-test/node_modules/mocha/lib/runner.js:443:10)
    at /mnt/c/Users/kwozniak/Documents/application-master-test/node_modules/mocha/lib/runner.js:549:12
    at next (/mnt/c/Users/kwozniak/Documents/application-master-test/node_modules/mocha/lib/runner.js:361:14)
    at /mnt/c/Users/kwozniak/Documents/application-master-test/node_modules/mocha/lib/runner.js:371:7
    at next (/mnt/c/Users/kwozniak/Documents/application-master-test/node_modules/mocha/lib/runner.js:295:14)
    at Immediate._onImmediate (/mnt/c/Users/kwozniak/Documents/application-master-test/node_modules/mocha/lib/runner.js:339:5)
    at processImmediate [as _immediateCallback] (timers.js:383:17)`
    `5) Open page with bank holidays`

Additionally, not sure if it is connected, I am getting the same errors as in the previous topic ( #165 ) , but this time deleting the file does not help. 
Any help will be very appreciated.

**Comment by zelfick** [comment]
I am getting error when i run npm test on the same part:
CRUD for bank holidays
    4) Performing registration process
Unhandled rejection TypeError: Cannot read property 'get' of undefined

any ideas

**Comment by zelfick** [comment]
It seems that the test failing because there isn't ready the url (/root/timeoff-management/t/lib/open_page.js):

'use strict';

var webdriver = require('selenium-webdriver'),
    Promise   = require("bluebird");

module.exports = Promise.promisify( function(args, callback){

  var url             = args.url,
      driver          = args.driver,
      result_callback = callback;

  // Open front page
  driver
    .get( url )
    .then(function(){
      // "export" current driver
      result_callback(
        null,
        {
          driver : driver,
        }
      );
    });

**Comment by dvillarraga** [comment]
Did you find how to solve it ? I am having the same issue!
