### ISSUE TITLE
Email notification failed: 432 4.3.2 STOREDRV.ClientSubmit; sender thread limit exceeded

### ISSUE THREAD

**Issue by wowitinc** [timeoff-management/application#308]
Hello,

   I've attempted to enable to email notification but the logs display the following errors:

`An error occured when user 4 try to create a leave request: Error: Message failed: 432 4.3.2 STOREDRV.ClientSubmit; sender thread limit exceeded [Hostname=DM5SPR00MB2471.namprd08.prod.outlook.com] at: Error: Message failed: 432 4.3.2 STOREDRV.ClientSubmit; sender thread limit exceeded [Hostname=DM5SPR00MB2471.namprd08.prod.outlook.com]
    at SMTPConnection._formatError (C:\timeoff-management\node_modules\smtp-connection\src\smtp-connection.js:384:15)
    at SMTPConnection._actionStream (C:\timeoff-management\node_modules\smtp-connection\src\smtp-connection.js:963:30)
    at SMTPConnection.<anonymous> (C:\timeoff-management\node_modules\smtp-connection\src\smtp-connection.js:594:14)
    at SMTPConnection._processResponse (C:\timeoff-management\node_modules\smtp-connection\src\smtp-connection.js:516:16)
    at SMTPConnection._onData (C:\timeoff-management\node_modules\smtp-connection\src\smtp-connection.js:353:10)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:601:20)`

The code within the app.json file is:
`{
   "allow_create_new_accounts" : true,
   "send_emails"              : true,
   "application_sender_email" : "email@domain.com",
   "email_transporter" : {
      "host" : "SMTP.office365.com",
      "port" : 25,
      "secure" : false,
      "ignoreTLS" : false,
      "auth" : {
         "user" : "email@domain.com",
         "pass" : "mypassword"
      },
      "tls" : {
         "ciphers" : "SSLv3"
      }
},
 "ga_analytics_on" : false,
 "crypto_secret" : "!2~`HswpPPLa22+=±§sdq qwe,appp qwwokDF_",
 "application_domain" : "http://app.timeoff.management",
 "promotion_website_domain" : "http://timeoff.management"
}`

There is a Microsoft announcement that mentions this error but I can't see how the limit could be exceeded in the context of the timeoff-management application [https://blogs.technet.microsoft.com/exchange/2018/04/20/changes-coming-to-the-smtp-authenticated-submission-client-protocol/].

Any information / suggestions would be greatly appreciated.

Thank you,
Dee

**Comment by vpp** [comment]
Hi Dee,

This looks like an issue with email sending facilities outside TOM application. 

Let’s keep this issue open as there are quite few people around who use this app with MS  infrastructure, so maybe they will be able to help.

Thanks
Pavlo

**Comment by wowitinc** [comment]
Hi Pavlo,  Just an FYI for others - even though the error is thrown (and, of course, TOM reflects that with an error notification to the user), the email DOES actually get sent.

**Comment by mudasir111** [comment]
@wowitinc 
In my application, i observe mail is not sent.
