### ISSUE TITLE
Errors when email notifications are enabled - TypeError: Cannot read property 'getSocket' of undefined 

### ISSUE THREAD

**Issue by cosmo145** [timeoff-management/application#323]
Having issues getting email notifications to work.  

Below is the output after requesting a new absence

express deprecated req.param(name): Use req.params, req.body, or req.query instead lib/route/validator/leave_request.js:11:46
express deprecated req.param(name): Use req.params, req.body, or req.query instead lib/route/validator/leave_request.js:12:46
express deprecated req.param(name): Use req.params, req.body, or req.query instead lib/route/validator/leave_request.js:13:46
express deprecated req.param(name): Use req.params, req.body, or req.query instead lib/route/validator/leave_request.js:14:46
express deprecated req.param(name): Use req.params, req.body, or req.query instead lib/route/validator/leave_request.js:15:46
express deprecated req.param(name): Use req.params, req.body, or req.query instead lib/route/validator/leave_request.js:16:46
express deprecated req.param(name): Use req.params, req.body, or req.query instead lib/route/validator/leave_request.js:17:46
An error occured when user 1 try to create a leave request: TypeError: Cannot read property 'getSocket' of undefined at: TypeError: Cannot read property 'getSocket' of undefined
    at sendMail (/home/dsalerno/vacations/timeoff-management/node_modules/nodemailer/lib/mailer/index.js:145:25)
    at tryCatcher (/home/dsalerno/vacations/timeoff-management/node_modules/bluebird/js/release/util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (/home/dsalerno/vacations/timeoff-management/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at /home/dsalerno/vacations/timeoff-management/lib/email.js:272:12
    at tryCatcher (/home/dsalerno/vacations/timeoff-management/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/dsalerno/vacations/timeoff-management/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/dsalerno/vacations/timeoff-management/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/dsalerno/vacations/timeoff-management/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/dsalerno/vacations/timeoff-management/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/dsalerno/vacations/timeoff-management/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/dsalerno/vacations/timeoff-management/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/dsalerno/vacations/timeoff-management/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/dsalerno/vacations/timeoff-management/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
express deprecated req.param(name): Use req.params, req.body, or req.query instead lib/route/calendar.js:92:15
express deprecated req.param(name): Use req.params, req.body, or req.query instead lib/route/calendar.js:93:19
POST /calendar/bookleave/ 302 850.742 ms - 64
GET /css/bootstrap.min.css 304 1.075 ms - -
GET /css/font-awesome.min.css 304 1.511 ms - -
GET /css/style.css 304 1.417 ms - -
GET /css/bootstrap-datepicker3.standalone.css 304 0.325 ms - -
GET /calendar/ 200 204.460 ms - 74846
GET /fonts/fontawesome-webfont.woff2?v=4.4.0 304 0.393 ms - -
GET /js/bootstrap-datepicker.js 304 0.954 ms - -
GET /js/jquery.min.js 304 2.474 ms - -
GET /js/bootstrap.min.js 304 2.543 ms - -
GET /js/global.js 304 2.431 ms - -

**Comment by vpp** [comment]
Very likely something is wrong with email configuration.
