### ISSUE TITLE
Errors when running db-update

### ISSUE THREAD

**Issue by call-tomorrow** [timeoff-management/application#332]
Hello.

I am trying to update app in production using `npm run-script db-update` statement as mentioned in readme "Updating existing instance with new code" section. I am walk through these steps (`git fetch` --> `git pull origin master` --> `npm install`) and finally got stuck on  `npm run-script db-update`

The error is:

```
npm run-script db-update

> TimeOff.Management@0.10.0 db-update /opt/timeoff-management
> node node_modules/.bin/sequelize db:migrate --config=config/db.json --models-path=lib/model/db/


Sequelize [Node: 6.16.0, CLI: 2.5.1, ORM: 3.33.0, sqlite3: ^3.1.1]

Loaded configuration file "config/db.json".
Using environment "development".
== 20190118-chnage-type-value-for-api-token: migrating =======
TypeError: Cannot read property 'type' of undefined
    at queryInterface.describeTable.then.attributes (/opt/timeoff-management/migrations/20190118-chnage-type-value-for-api-token.js:11:43)
    at tryCatcher (/opt/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/opt/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/opt/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/opt/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/opt/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

npm ERR! Linux 3.10.0-862.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run-script" "db-update"
npm ERR! node v6.16.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! TimeOff.Management@0.10.0 db-update: `node node_modules/.bin/sequelize db:migrate --config=config/db.json --models-path=lib/model/db/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the TimeOff.Management@0.10.0 db-update script 'node node_modules/.bin/sequelize db:migrate --config=config/db.json --models-path=lib/model/db/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the TimeOff.Management package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/.bin/sequelize db:migrate --config=config/db.json --models-path=lib/model/db/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs TimeOff.Management
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls TimeOff.Management
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/timeoff-management/lib/model/db/npm-debug.log
```

Am I missing something? Thanks in advance!

**Comment by vpp** [comment]
This is weird... I suspect that migrations were run in wrong order...

Can you please send me output of this query:|
```
select * from SequelizeMeta order by 1
```

(this is not sensitive data and contains only list of migrations taht where applied to you database)

**Comment by call-tomorrow** [comment]
```
select * from SequelizeMeta order by 1;
20170103144054-add_default_date_format.js
20170329060832-rename_allowence_to_allowance.js
20170530-add_auto_approve_flag_to_user.js
20171218-company-wide-message.js
20171219-allowance-adjustment-per-year.js
20171220-drop-adjustment-column-from-user.js
20171222-add-carry-over-allowance-column.js
20171228-add-time-zone-field-to-company.js
20180102-company-mode.js
20180103-sort-order-for-leave-types.js
20180427-add-is_accrued_allowance-to-department.js
20181119-integration-api-token-per-company.js
20181213-carry-over-conf.js
```

**Comment by AsimPervez93** [comment]
I'm having the same issue

**Comment by gazben** [comment]
@AsimPervez93 
Log in to the database and this will solve it:
`ALTER TABLE 'Companies' ADD integration_api_token 'UUID' ;`

**Comment by AsimPervez93** [comment]
> @AsimPervez93 @call-tomorrow
> Log in to the database and this will solve it:
> `ALTER TABLE 'Companies' ADD integration_api_token 'UUID' ;`

Thanks @gazben this resolved my issue!  Although I'm now having [this issue](https://github.com/timeoff-management/application/issues/295)

**Comment by gazben** [comment]
@AsimPervez93 Same here. I asked the users to reset.
