### ISSUE TITLE
Crash using LDAP

### ISSUE THREAD

**Issue by vitas** [timeoff-management/application#334]
I have configured LDAP auth what works fine, but the app crashes after few minutes without any error in UI. Strange as configuration is correct and user can login and use the app

events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onread (net.js:602:25)
Emitted 'error' event at:
    at LdapAuth._handleError (/opt/sonar/timeoff-management/node_modules/ldapauth-fork/lib/ldapauth.js:171:8)
    at Client.emit (events.js:180:13)
    at Socket.onSocketError (/opt/sonar/timeoff-management/node_modules/ldapjs/lib/client/client.js:1169:12)
    at Socket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TimeOff.Management@0.10.0 start: `node bin/wwww`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the TimeOff.Management@0.10.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by vitas** [comment]
this happens if AD closes connection and  the app tries to delete the session

**Comment by vpp** [comment]
hi @vitas, to mitigate the issue one can use `node bin/wwww_cluster` so app runs as cluster of processes rather then single one, and eash failing one is restrted automatically.

**Comment by blewie** [comment]
Hello,
Having the same issue. I tried to start the application with "npm start node bin/www_cluster". This will work until the first person starts to authenticate. The app will crash within minutes.
