### ISSUE TITLE
Can't seem to start npm test -- what am i missing?

### ISSUE THREAD

**Issue by sampelje** [timeoff-management/application#344]
JSampel@JSAMPELP51 MINGW64 /c/timeoff (master)
$ npm test

> TimeOff.Management@0.10.0 test C:\timeoff
> node node_modules/mocha/bin/mocha --recursive t/*

module.js:549
    throw err;
    ^

Error: Cannot find module 'C:\timeoff\t\integration'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at C:\timeoff\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\timeoff\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (C:\timeoff\node_modules\mocha\lib\mocha.js:514:10)
    at Object.<anonymous> (C:\timeoff\node_modules\mocha\bin\_mocha:480:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! Test failed.  See above for more details.

JSampel@JSAMPELP51 MINGW64 /c/timeoff (master)
$

**Comment by vpp** [comment]
Weird... Not sure I can help with it as do not have access to any Windows machine...

**Comment by jdambron** [comment]
@sampelje the error you experienced should be resolved.
Can you confirm please ?

**Comment by jdambron** [comment]
@vpp I think this issue can be closed. Tests work fine for me on Windows now.
