### ISSUE TITLE
Unhandled Rejection when running npm start

### ISSUE THREAD

**Issue by AsimPervez93** [timeoff-management/application#349]
Hi all, I'm trying to get the app running on a new server but I get the below, any ideas?

running `npm start` returns this error

Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: no such column: companyId
    at Query.formatError (/var/www/html/timeoff-management/node_modules/sequelize/lib/dialects/sqlite/query.js:419:16)
    at Query._handleQueryResponse (/var/www/html/timeoff-management/node_modules/sequelize/lib/dialects/sqlite/query.js:73:18)
    at afterExecute (/var/www/html/timeoff-management/node_modules/sequelize/lib/dialects/sqlite/query.js:247:31)
    at replacement (/var/www/html/timeoff-management/node_modules/sqlite3/lib/trace.js:19:31)
    at Statement.errBack (/var/www/html/timeoff-management/node_modules/sqlite3/lib/sqlite3.js:16:21)

**Comment by vpp** [comment]
Please ensure you have node 6 on that server.

Thanks
Pavlo

**Comment by AsimPervez93** [comment]
Thanks @vpp

**Comment by AsimPervez93** [comment]
I've had a repeat of this error:

`Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: no such column: companyId
    at Query.formatError (/var/www/html/timeoff-management/node_modules/sequelize/lib/dialects/sqlite/query.js:418:16)
    at Query._handleQueryResponse (/var/www/html/timeoff-management/node_modules/sequelize/lib/dialects/sqlite/query.js:72:18)
    at afterExecute (/var/www/html/timeoff-management/node_modules/sequelize/lib/dialects/sqlite/query.js:246:31)
    at replacement (/var/www/html/timeoff-management/node_modules/sqlite3/lib/trace.js:19:31)
    at Statement.errBack (/var/www/html/timeoff-management/node_modules/sqlite3/lib/sqlite3.js:16:21)`

I'm running:
node v8.16.1
npm 6.4.1

Anyone able to suggest anything?

**Comment by vpp** [comment]
Try to run DB migrations (from within root of the application):
```
node node_modules/.bin/sequelize db:migrate --config=config/db.json --models-path=lib/model/db/
```

**Comment by AsimPervez93** [comment]
@vpp This is a new installation so I haven't migrated any DB or anything.  It's a completely new setup.

I ran the DB migration one liner you mentioned but got the below: (I'm guessing this is because there isn't a database to migrate)

Sequelize CLI [Node: 8.16.1, CLI: 5.5.1, ORM: 6.0.0]

Loaded configuration file "config/db.json".
Using environment "development".
== 20170103144054-add_default_date_format: migrating =======

ERROR: Migration 20170103144054-add_default_date_format.js (or wrapper) didn't return a promise

**Comment by vpp** [comment]
`node` is too recent: `8.16.1`.

App is not ready yet for this version: please downgrade to the `6.14.4`

**Comment by AsimPervez93** [comment]
@vpp Thanks! Legend as always

I used nvm to downgrade to node 6.14.4 and everything went swimmingly.

Up and running now!
