### ISSUE TITLE
fail db migration for 0.10

### ISSUE THREAD

**Issue by druidtides** [timeoff-management/application#372]
I was trying to update my package and ran into this error

[ec2-user@ip-172-31-11-80 timeoff-management]$ npm run-script db-update

> TimeOff.Management@0.10.0 db-update /home/ec2-user/timeoff-management
> node node_modules/.bin/sequelize db:migrate --config=config/db.json --models-path=lib/model/db/

Sequelize [Node: 8.0.0, CLI: 2.5.1, ORM: 3.32.1, sqlite3: ^3.1.1]

Loaded configuration file "config/db.json".
Using environment "development".
== 20190118-chnage-type-value-for-api-token: migrating =======
TypeError: Cannot read property 'type' of undefined
    at queryInterface.describeTable.then.attributes (/home/ec2-user/timeoff-management/migrations/20190118-chnage-type-value-for-api-token.js:11:43)
    at tryCatcher (/home/ec2-user/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ec2-user/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ec2-user/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ec2-user/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ec2-user/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/ec2-user/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ec2-user/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/ec2-user/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TimeOff.Management@0.10.0 db-update: `node node_modules/.bin/sequelize db:migrate --config=config/db.json --models-path=lib/model/db/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the TimeOff.Management@0.10.0 db-update script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2019-09-10T11_18_06_609Z-debug.log

**Comment by osc86** [comment]
The migration script doesn't seem to work with mariadb:

> /app/timeoff-management # node node_modules/.bin/sequelize db:migrate --config=config/db.json --models-path=lib/model/db/
> 
> Sequelize [Node: 6.10.3, CLI: 2.5.1, ORM: 3.34.0]
> 
> Loaded configuration file "config/db.json".
> Using environment "development".
> == 20190118-chnage-type-value-for-api-token: migrating =======
> { SequelizeDatabaseError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'PRAGMA foreign_keys=off' at line 1
>     at Query.formatError (/app/timeoff-management/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
>     at Query.<anonymous> (/app/timeoff-management/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
>     at Query.<anonymous> (/app/timeoff-management/node_modules/mysql/lib/Connection.js:502:10)
>     at Query._callback (/app/timeoff-management/node_modules/mysql/lib/Connection.js:468:16)
>     at Query.Sequence.end (/app/timeoff-management/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
>     at Query.ErrorPacket (/app/timeoff-management/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
>     at Protocol._parsePacket (/app/timeoff-management/node_modules/mysql/lib/protocol/Protocol.js:278:23)
>     at Parser.write (/app/timeoff-management/node_modules/mysql/lib/protocol/Parser.js:76:12)
>     at Protocol.write (/app/timeoff-management/node_modules/mysql/lib/protocol/Protocol.js:38:16)
>     at Socket.<anonymous> (/app/timeoff-management/node_modules/mysql/lib/Connection.js:91:28)
>     at Socket.<anonymous> (/app/timeoff-management/node_modules/mysql/lib/Connection.js:502:10)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:188:7)
>     at readableAddChunk (_stream_readable.js:176:18)
>     at Socket.Readable.push (_stream_readable.js:134:10)
>     at TCP.onread (net.js:547:20)
>   name: 'SequelizeDatabaseError',
>   message: 'ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'PRAGMA foreign_keys=off\' at line 1',
>   parent: 
>    { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'PRAGMA foreign_keys=off' at line 1
>        at Query.Sequence._packetToError (/app/timeoff-management/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
>        at Query.ErrorPacket (/app/timeoff-management/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
>        at Protocol._parsePacket (/app/timeoff-management/node_modules/mysql/lib/protocol/Protocol.js:278:23)
>        at Parser.write (/app/timeoff-management/node_modules/mysql/lib/protocol/Parser.js:76:12)
>        at Protocol.write (/app/timeoff-management/node_modules/mysql/lib/protocol/Protocol.js:38:16)
>        at Socket.<anonymous> (/app/timeoff-management/node_modules/mysql/lib/Connection.js:91:28)
>        at Socket.<anonymous> (/app/timeoff-management/node_modules/mysql/lib/Connection.js:502:10)
>        at emitOne (events.js:96:13)
>        at Socket.emit (events.js:188:7)
>        at readableAddChunk (_stream_readable.js:176:18)
>        at Socket.Readable.push (_stream_readable.js:134:10)
>        at TCP.onread (net.js:547:20)
>        --------------------
>        at Protocol._enqueue (/app/timeoff-management/node_modules/mysql/lib/protocol/Protocol.js:144:48)
>        at Connection.query (/app/timeoff-management/node_modules/mysql/lib/Connection.js:200:25)
>        at /app/timeoff-management/node_modules/sequelize/lib/dialects/mysql/query.js:40:21
>        at Promise._execute (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/debuggability.js:313:9)
>        at Promise._resolveFromExecutor (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:483:18)
>        at new Promise (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:79:10)
>        at Query.run (/app/timeoff-management/node_modules/sequelize/lib/dialects/mysql/query.js:39:17)
>        at /app/timeoff-management/node_modules/sequelize/lib/sequelize.js:849:20
>        at /app/timeoff-management/node_modules/retry-as-promised/index.js:39:21
>        at Promise._execute (/app/timeoff-management/node_modules/retry-as-promised/node_modules/bluebird/js/release/debuggability.js:313:9)
>        at Promise._resolveFromExecutor (/app/timeoff-management/node_modules/retry-as-promised/node_modules/bluebird/js/release/promise.js:483:18)
>        at new Promise (/app/timeoff-management/node_modules/retry-as-promised/node_modules/bluebird/js/release/promise.js:79:10)
>        at retryAsPromised (/app/timeoff-management/node_modules/retry-as-promised/index.js:29:10)
>        at /app/timeoff-management/node_modules/sequelize/lib/sequelize.js:848:12
>        at tryCatcher (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
>        at Promise._settlePromiseFromHandler (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:512:31)
>        at Promise._settlePromise (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:569:18)
>        at Promise._settlePromise0 (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:614:10)
>        at Promise._settlePromises (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:694:18)
>        at _drainQueueStep (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/async.js:138:12)
>        at _drainQueue (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/async.js:131:9)
>        at Async._drainQueues (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/async.js:147:5)
>        at Immediate.Async.drainQueues (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)
>        at runCallback (timers.js:672:20)
>        at tryOnImmediate (timers.js:645:5)
>        at processImmediate [as _immediateCallback] (timers.js:617:5)
>      code: 'ER_PARSE_ERROR',
>      errno: 1064,
>      sqlMessage: 'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'PRAGMA foreign_keys=off\' at line 1',
>      sqlState: '42000',
>      index: 0,
>      sql: 'PRAGMA foreign_keys=off;' },
>   original: 
>    { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'PRAGMA foreign_keys=off' at line 1
>        at Query.Sequence._packetToError (/app/timeoff-management/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
>        at Query.ErrorPacket (/app/timeoff-management/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
>        at Protocol._parsePacket (/app/timeoff-management/node_modules/mysql/lib/protocol/Protocol.js:278:23)
>        at Parser.write (/app/timeoff-management/node_modules/mysql/lib/protocol/Parser.js:76:12)
>        at Protocol.write (/app/timeoff-management/node_modules/mysql/lib/protocol/Protocol.js:38:16)
>        at Socket.<anonymous> (/app/timeoff-management/node_modules/mysql/lib/Connection.js:91:28)
>        at Socket.<anonymous> (/app/timeoff-management/node_modules/mysql/lib/Connection.js:502:10)
>        at emitOne (events.js:96:13)
>        at Socket.emit (events.js:188:7)
>        at readableAddChunk (_stream_readable.js:176:18)
>        at Socket.Readable.push (_stream_readable.js:134:10)
>        at TCP.onread (net.js:547:20)
>        --------------------
>        at Protocol._enqueue (/app/timeoff-management/node_modules/mysql/lib/protocol/Protocol.js:144:48)
>        at Connection.query (/app/timeoff-management/node_modules/mysql/lib/Connection.js:200:25)
>        at /app/timeoff-management/node_modules/sequelize/lib/dialects/mysql/query.js:40:21
>        at Promise._execute (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/debuggability.js:313:9)
>        at Promise._resolveFromExecutor (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:483:18)
>        at new Promise (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:79:10)
>        at Query.run (/app/timeoff-management/node_modules/sequelize/lib/dialects/mysql/query.js:39:17)
>        at /app/timeoff-management/node_modules/sequelize/lib/sequelize.js:849:20
>        at /app/timeoff-management/node_modules/retry-as-promised/index.js:39:21
>        at Promise._execute (/app/timeoff-management/node_modules/retry-as-promised/node_modules/bluebird/js/release/debuggability.js:313:9)
>        at Promise._resolveFromExecutor (/app/timeoff-management/node_modules/retry-as-promised/node_modules/bluebird/js/release/promise.js:483:18)
>        at new Promise (/app/timeoff-management/node_modules/retry-as-promised/node_modules/bluebird/js/release/promise.js:79:10)
>        at retryAsPromised (/app/timeoff-management/node_modules/retry-as-promised/index.js:29:10)
>        at /app/timeoff-management/node_modules/sequelize/lib/sequelize.js:848:12
>        at tryCatcher (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
>        at Promise._settlePromiseFromHandler (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:512:31)
>        at Promise._settlePromise (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:569:18)
>        at Promise._settlePromise0 (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:614:10)
>        at Promise._settlePromises (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:694:18)
>        at _drainQueueStep (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/async.js:138:12)
>        at _drainQueue (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/async.js:131:9)
>        at Async._drainQueues (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/async.js:147:5)
>        at Immediate.Async.drainQueues (/app/timeoff-management/node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)
>        at runCallback (timers.js:672:20)
>        at tryOnImmediate (timers.js:645:5)
>        at processImmediate [as _immediateCallback] (timers.js:617:5)
>      code: 'ER_PARSE_ERROR',
>      errno: 1064,
>      sqlMessage: 'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'PRAGMA foreign_keys=off\' at line 1',
>      sqlState: '42000',
>      index: 0,
>      sql: 'PRAGMA foreign_keys=off;' },
>   sql: 'PRAGMA foreign_keys=off;' }
