### ISSUE TITLE
Fix a ugly output ini tests

### ISSUE THREAD

**Issue by vpp** [timeoff-management/application#40]
There are some moment.js usage that is going to be deprecated, following is from test runs:

  Basic leave request
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
Arguments: [object Object]
Error
    at Function.createFromInputFallback (/home/travis/tom/node_modules/moment/moment.js:850:105)
    at configFromString (/home/travis/tom/node_modules/moment/moment.js:970:32)
    at configFromInput (/home/travis/tom/node_modules/moment/moment.js:1473:13)
    at prepareConfig (/home/travis/tom/node_modules/moment/moment.js:1456:13)
    at createFromConfig (/home/travis/tom/node_modules/moment/moment.js:1423:44)
    at createLocalOrUTC (/home/travis/tom/node_modules/moment/moment.js:1505:16)
    at local__createLocal (/home/travis/tom/node_modules/moment/moment.js:1509:16)
    at utils_hooks__hooks (/home/travis/tom/node_modules/moment/moment.js:16:29)
    at /home/travis/tom/lib/model/mixin/user/absence_aware.js:24:16
    at Function._.map._.collect (/home/travis/tom/node_modules/underscore/underscore.js:172:24)
    at _get_calendar_months_to_show (/home/travis/tom/lib/model/mixin/user/absence_aware.js:23:16)
    at promise_calendar (/home/travis/tom/lib/model/mixin/user/absence_aware.js:42:36)
    at router.get.base_date (/home/travis/tom/lib/route/calendar.js:107:14)
    at Layer.handle [as handle_request](/home/travis/tom/node_modules/express/lib/router/layer.js:82:5)
    at next (/home/travis/tom/node_modules/express/lib/router/route.js:100:13)
    at Route.dispatch (/home/travis/tom/node_modules/express/lib/router/route.js:81:3)
    at Layer.handle [as handle_request](/home/travis/tom/node_modules/express/lib/router/layer.js:82:5)
    at /home/travis/tom/node_modules/express/lib/router/index.js:234:24
    at Function.proto.process_params (/home/travis/tom/node_modules/express/lib/router/index.js:312:12)
    at /home/travis/tom/node_modules/express/lib/router/index.js:228:12
    at Function.match_layer (/home/travis/tom/node_modules/express/lib/router/index.js:295:3)
    at next (/home/travis/tom/node_modules/express/lib/router/index.js:189:10)
    at /home/travis/tom/node_modules/express/lib/router/index.js:191:16
    at Function.match_layer (/home/travis/tom/node_modules/express/lib/router/index.js:295:3)

**Comment by vpp** [comment]
Looks like this is not an issue any more.

Closing...
