### ISSUE TITLE
PM2 run error, works with npm 

### ISSUE THREAD

**Issue by mambli** [timeoff-management/application#414]
Hi,

i really love this application. At the moment i'm just testing it. 
When i run the application with npm start wwww, application starts and works as it should. But if i try to run it with pm2, it's start, but in the browser i get the error:
`Error: Failed to lookup view "error" in views directory "/var/www/timeoff-management/bin/views"
    at Function.render (/var/www/timeoff-management/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/var/www/timeoff-management/node_modules/express/lib/response.js:1012:7)
    at /var/www/timeoff-management/app.js:180:9
    at Layer.handle_error (/var/www/timeoff-management/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/www/timeoff-management/node_modules/express/lib/router/index.js:315:13)
    at /var/www/timeoff-management/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/timeoff-management/node_modules/express/lib/router/index.js:335:12)
    at IncomingMessage.next (/var/www/timeoff-management/node_modules/express/lib/router/index.js:275:10)
    at done (/var/www/timeoff-management/node_modules/express/lib/response.js:1007:25)
    at Function.render (/var/www/timeoff-management/node_modules/express/lib/application.js:582:14)
    at ServerResponse.render (/var/www/timeoff-management/node_modules/express/lib/response.js:1012:7)
    at /var/www/timeoff-management/app.js:169:13
    at Layer.handle_error (/var/www/timeoff-management/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/www/timeoff-management/node_modules/express/lib/router/index.js:315:13)
    at /var/www/timeoff-management/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/timeoff-management/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/timeoff-management/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/timeoff-management/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/timeoff-management/node_modules/express/lib/router/index.js:315:13)
    at /var/www/timeoff-management/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/timeoff-management/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/timeoff-management/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/timeoff-management/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/timeoff-management/node_modules/express/lib/router/index.js:315:13)
    at /var/www/timeoff-management/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/timeoff-management/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/timeoff-management/node_modules/express/lib/router/index.js:275:10)
    at /var/www/timeoff-management/node_modules/express/lib/router/index.js:635:15`

any idea? 

Thanks for you work.

**Comment by vpp** [comment]
not sure why....

Did not try the app with `pm2`.

Maybe other people have more experience with that.

**Comment by mambli** [comment]
Hi, thanks for quick reply. I also get the same error with `forever`. 
Maybe someone else had the same issue. 

Do you run Timeoff.management with Systemd?

Thanks

**Comment by vpp** [comment]
One way to run is:
```
nohup node bin/wwww_cluster >> <path/to/log>  2>&1 &
```

**Comment by vpp** [comment]
Looks like question is resolved
